from sc2.constants import *

TECH_STRUCTURES = {
    UnitTypeId.FORGE,
    UnitTypeId.CYBERNETICSCORE,
    UnitTypeId.TEMPLARARCHIVE,
    UnitTypeId.DARKSHRINE,
    UnitTypeId.TWILIGHTCOUNCIL,
    UnitTypeId.FLEETBEACON,
    UnitTypeId.ROBOTICSBAY
}

BUILDING_STRUCTURES = {
    UnitTypeId.NEXUS,
    UnitTypeId.GATEWAY,
    UnitTypeId.WARPGATE,
    UnitTypeId.STARGATE,
    UnitTypeId.ROBOTICSFACILITY,
}

DEF_STRUCTURES = {
    UnitTypeId.SHIELDBATTERY,
    UnitTypeId.PHOTONCANNON
}

POWERED_STRUCTURES = TECH_STRUCTURES | BUILDING_STRUCTURES | DEF_STRUCTURES
